# Generated by Django 4.1 on 2022-08-31 19:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_alter_routes_options_alter_routes_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='static', verbose_name='Фото')),
                ('desc', models.TextField(max_length=250, verbose_name='Описание')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Публикация')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Маршруты',
                'verbose_name_plural': 'Маршруты',
                'ordering': ['-publish', 'title'],
            },
        ),
        migrations.DeleteModel(
            name='Routes',
        ),
    ]
