# Generated by Django 4.1 on 2022-09-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_post_delete_routes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish', 'title'], 'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршруты'},
        ),
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=models.TextField(max_length=100, verbose_name='Описание'),
        ),
    ]
