# Generated by Django 4.1 on 2022-09-04 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_comment_alter_post_desc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
